### ISSUE TITLE
Error - Factor mes

### ISSUE THREAD

**Issue by KristianMC** [barja8/quickly_rgee#1]
Hola @barja8, he encontrado un error en tu codigo.
![Imagen_error](https://user-images.githubusercontent.com/60116463/89117541-1f968e00-d464-11ea-905f-f9146becf411.jpg)

**Comment by ambarja** [comment]
Gracias @KristianMC , ahora si el code ha sido modificado, solo ten presente que en la función: 
```r
lista <- img_available(id = names_id,
                       path = 4, 
                       row = 71,
                       cloud = 1)
```
cloud representa al %  de nubes menor a 1 (cloud < 1), si pones 0 , representaria  cloud < 0 , y saldría error debido a que no hay valores negativos.
Gracias!
